### ISSUE TITLE
command e and escape vs. command m, g, h, j

### ISSUE THREAD

**Issue by 18nshinagawa** [18nshinagawa/notes#63]
task for @lzhangix :

show someone, maybe A, how to use this app

then ask them whether command m, g, h, j are more intuitive for editing and closing.

if they say yes, then I will mplement the change (majority rules in favor of @lzhangix 's original suggestion and I will honor it)

otherwise, it'll be kept this way for now

**Comment by 18nshinagawa** [comment]
although either way, escape will be kept since it's intuitive; more of a matter of support for the command m, etc. and whether to get rid of command e or not

**Comment by lzhaxi** [comment]
The reason that this makes sense to me is not because I want to use it when I want to write a larger math equation, it's when I want it in the same line. For example in class today, I have:
Let x_1, ..., x_n be a sample of n observations.
I want to type command + m to get into math and my fingers are already there, it's easier to type command + m to get out of math if I just want to type like a variable in math, not necessarily a full equation. If I wanted to type a full equation, escape would be fine, but because sometimes I want to just type a variable, escape is just so slow.
For clarity: in that example, I would want x_1 to x_n to be in math, then n to be in math (to keep the style the same).

**Comment by 18nshinagawa** [comment]
Especially with command + k toggling, I think i've decided this is good.

**Comment by 18nshinagawa** [comment]
make the editing part of suggestion part of #62
