### ISSUE TITLE
≠ sign

### ISSUE THREAD

**Issue by lzhaxi** [18nshinagawa/notes#74]
≠ does not look correct in the app

**Comment by 18nshinagawa** [comment]
looking at this  and it seems easily fixable but I can't find why it's happening

i know a temporary fix but want a permanent one

**Comment by 18nshinagawa** [comment]
this hopefully isn't an issue for other similar characters but will test

**Comment by 18nshinagawa** [comment]
just tested it in katex main page by creating a custom iframe and injecting;

same result meaning this is a katex issue.

**Comment by 18nshinagawa** [comment]
@lzhangix can you help me submit the bug to KaTeX?

I know how to reproduce the error but I don't have the time to read through their bug reporting rules/formatting, so if you could help, that'd be great

this is the only real way to fix the bug

**Comment by lzhaxi** [comment]
@18nshinagawa you're gonna have to do the majority of it I don't know anything about the error

**Comment by 18nshinagawa** [comment]
@lzhangix lol alright but can you proof it and check, and also submit because i don't want attention?

**Comment by 18nshinagawa** [comment]
but wait. it might not actually be just the iframe; testing other methods

**Comment by 18nshinagawa** [comment]
i tried but can't think of anything;

anyway, here it is:

https://codepen.io/anon/pen/XLvvvL

**Comment by 18nshinagawa** [comment]
> Before reporting a bug
- [x] Check [common issues](https://katex.org/docs/issues.html).
- [x] Check the bug is reproducible in [the demo](https://katex.org). If not, check KaTeX is up-to-date and installed correctly.
- [x] Search for [existing issues](https://github.com/KaTeX/KaTeX/issues).

**Describe the bug:**
As the title says,` \not =`, `\neq`, `\ne`, etc. are not aligned correctly inside the iframe even though it loads fine outside an iframe; other things don't seem to have issues, including fractions, which seems to have been reported before

**(La)TeX code:**
The code of (La)TeX you tried to render:
```latex
a \ne b
a \neq b
a \not = b
```
(in math mode, both display and inline)

**Expected behavior:**
i'd expect it to look the same inside and outside an iframe because everything else seems to do that

**Screenshots:**
https://codepen.io/anon/pen/XLvvvL

**Environment (please complete the following information):**
 - KaTeX Version: 0.10.2
 - Device: MacBook Air 2018
 - OS: OSX Mojave (10.14.5)
 - Browser: FireFox 68.0, Safari 12.1.1,  Chrome 75.0.3770.142
 - Version: see above?

**Additional context:**
n/a

**Comment by 18nshinagawa** [comment]
you should be able to edit/copy source of the above; thanks!!!

**Comment by 18nshinagawa** [comment]
\not =, \neq, \ne, etc. not aligned correctly inside iframe [pen included] for title

https://github.com/KaTeX/KaTeX/issues

**Comment by 18nshinagawa** [comment]
@lzhangix ready to submit!

**Comment by 18nshinagawa** [comment]
submitted under alt account nsheep755 @lzhangix please remind me to check back occasionally

**Comment by 18nshinagawa** [comment]
i think our job here is done so just wait for the next katex version upate

**Comment by 18nshinagawa** [comment]
got response from katex developer who acknowledged the issue; responded to them; will update after next response from them
